#!/usr/bin/env bash
# A script that installs nginx

sudo apt-get update
sudo apt-get install -y nginx

cat <<EOF | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    server_name _;
    location / {
        return 200 "Hello World!";
    }
}
EOF

sudo nginx -t

# Restart Nginx using the service command
sudo service nginx restart

# Check if Nginx is still running
if sudo service nginx status | grep -q "active (running)"; then
    echo "Nginx restarted successfully."
else
    echo "Nginx restart failed."
fi

sudo rm -f /var/www/html/index.nginx-debian.html
