#!/usr/bin/env bash
# 0-custom_http_response_header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create an Nginx custom configuration file
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $hostname;
    root /var/www/html;
    index index.html index.htm;
}' | sudo tee /etc/nginx/sites-available/custom_header > /dev/null

# Create a symbolic link to enable the custom configuration
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Remove the default Nginx configuration if it exists (optional)
sudo rm -f /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply the changes
sudo systemctl restart nginx

echo "Nginx configured with custom HTTP response header."
