#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# - Listens on port 80.
# - Returns a page containing "Hello World!" when queried
#   at the root with a curl GET request.
# - Configures /redirect_me as a "301 Moved Permanently".
# - Includes a custom 404 page containing "Ceci n'est pas une page".
# - Contains a custom HTTP header named X-Served-By.
# - The value of the HTTP header is the hostname of the running server.

# Check for root privileges
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root (sudo)." 
    exit 1
fi

# Install Nginx
apt-get update
apt-get install -y nginx

# Create web root directory and populate it
mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$hostname;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 https://YouTube.com/;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart

# Clean up
apt-get autoremove -y
apt-get clean

echo "Nginx installation and configuration completed."
