#!/usr/bin/env bash
# this script fixes the issue with Nginx not listening in port 80

#first we remove the default configuration file
rm /etc/nginx/sites-enabled/default

#then we coonfigure nginx to listen on port 80 for all active IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart the nginx
service nginx restart
