#!/usr/bin/env bash
# script that displays a list of currently running processes.

psaxjf > /tmp/process_tree.txt
echo "USER        PID  PPID  PGID  TTY        STAT  COMMAND"
awk '
  BEGIN { indent = 0 }
  {
    for (i = 0; i < indent; i++) printf("  ");
    printf("%-10s %5s %5s %5s %-10s %-4s %s\n", $1, $2, $3, $5, $6, $8, $9);
    indent = $4 - 2;
  }
' /tmp/process_tree.txt
rm /tmp/process_tree.txt
