#!/usr/bin/env bash

# Function to handle the SIGTERM signal
terminate_handler() {
    echo "I am invincible!!!"
    exit 0
}

# Register the terminate_handler function to handle SIGTERM
trap 'terminate_handler' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
