#!/usr/bin/env bash
#A script that configures an Ubuntu server with the below requirements.
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

# Check if the script is running with root privileges
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root. Use 'sudo' to execute it."
    exit 1
fi

# Define the hostnames and their corresponding IP addresses
localhost_ip="127.0.0.2"
facebook_ip="8.8.8.8"

# Configure the /etc/hosts file
echo -e "${localhost_ip}\tlocalhost" >> /etc/hosts
echo -e "${facebook_ip}\tfacebook.com" >> /etc/hosts

echo "Hosts configuration completed."
