#!/usr/bin/env bash
#A script that displays all active IPv4 IPs on the machine it’s executed on.

sudo ip addr show | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -v "127.0.0.1" | awk '{print $2}'
