#!/usr/bin/env bash
# Another implementation of 1-run_nginx_as_nginx

sed -i 's/^user.*/user nginx;/' /etc/nginx/nginx.conf
echo "server { listen *:8080; server_name _; location / { root /usr/share/nginx/html; index index.html index.htm; } }" > /etc/nginx/conf.d/default.conf
service nginx restart
