#!/usr/bin/env bash
# Another implementation of 1-run_nginx_as_nginx

pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
